sudo: required
dist: focal
services:
  - docker
language: generic
branches:
  only:
    - master
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project hexolink-4a945
  - gcloud config set compute/zone europe-central2
  - gcloud container clusters get-credentials hexolink
script:
  - mvn clean package

#для сборки самого проекта, каждый сервис собирается
#по отдельности, для пуша на докер хаб
after_success:
  - docker build -t noxior/auth-service:latest -t noxior/auth-service:$SHA -f ./auth-service/Dockerfile ./auth-service
  - docker build -t noxior/messenger:latest -t noxior/messenger:$SHA -f ./messenger/Dockerfile ./messenger
    #как раз место для пуша на докер хаб
    #login в докер хабе
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push noxior/auth-service:latest
  - docker push noxior/messenger:latest
  - docker push noxior/auth-service:$SHA
  - docker push noxior/messenger:$SHA
  - kubectl apply -f k8s
  - kubectl set image deployment/auth-service-deployment auth-service=noxior/auth-service:$SHA
  - kubectl set image deployment/messenger-deployment messenger=noxior/messenger:$SHA
