version: '3.3'
services:
#  nginx:
#    container_name: nginx
#    restart: always
#    volumes:
#      - ./nginx:/etc/nginx/ssl:ro
#    build:
#      dockerfile: Dockerfile.dev
#      context: ./nginx
#    depends_on:
#      - authentication-service
#    ports:
#      - "80:80"  # Пробрасываем порт 80 контейнера на порт 80 хоста
#      - "443:443"  # Пробрасываем порт 443 контейнера на порт 443 хоста
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: q987654321
      POSTGRES_USER: postgres
    ports:
    - "5432:5432"
    container_name: postgres_container
  rabbitmq:
    build: ./rabbitmq
    restart: always
    ports:
    - 5672:5672
    - 15672:15672
    - 61613:61613
    container_name: rabbitmq
#  authentication-service:
#    container_name: authentication-service
#    depends_on:
#      - postgres
#    build:
#      dockerfile: Dockerfile
#      context: ./authentication-service
#    ports:
#      - 3000:3000
#    restart: always
#    environment:
#      - PGUSER=postgres
#      - PGHOST=postgres
#      - PGDATABASE=postgres
#      - PGPASSWORD=q987654321
#      - PGPORT=5432
#  hexolink:
#    container_name: hexolink
#    depends_on:
#      - rabbitmq
#      - postgres
#    build:
#      dockerfile: Dockerfile
#      context: ./hexolink
#    ports:
#      - 5000:5000
#    restart: always
#    environment:
#      - RABBITMQ_HOST=rabbitmq
#      - PGUSER=postgres
#      - PGHOST=postgres
#      - PGDATABASE=postgres
#      - PGPASSWORD=q987654321
#      - PGPORT=5432
