apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - hexolink.xyz
        - www.hexolink.xyz
      secretName: hexolink-xyz
  rules:
    - host: hexolink.xyz
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service-cluster-ip-service
                port:
                  number: 3001
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: hexolink-cluster-ip-service
                port:
                  number: 6001
    - host: www.hexolink.xyz
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service-cluster-ip-service
                port:
                  number: 3001
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: hexolink-cluster-ip-service
                port:
                  number: 6001
