#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: rabbitmq-deployment
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      component: rabbitmq
#  template:
#    metadata:
#      labels:
#        component: rabbitmq
#    spec:
#      containers:
#        - name: rabbitmq
#          image: rabbitmq:3.9-management
#          ports:
#            - containerPort: 5672
#            - containerPort: 15672
#            - containerPort: 61613
#            - containerPort: 61614
#          volumeMounts:
#            - name: rabbitmq-config
#              mountPath: /etc/rabbitmq/
#          env:
#            - name: RABBITMQ_CONFIG_FILE
#              value: /etc/rabbitmq/rabbitmq
#      volumes:
#        - name: rabbitmq-config
#          configMap:
#            name: rabbitmq-config
#
#---
#
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: rabbitmq-config
#data:
#  rabbitmq: |
#    management.listener.port = 15672
#
#    listeners.tcp.default = 5672
#    listeners.tcp.internal = 5672
#
#    listeners.stomp.default = 61613
#    stomp.listeners.tcp.default = 61613
#    stomp.protocol_versions = "1.0 1.1 1.2"
#
#    management.load_definitions = /etc/rabbitmq/definitions.json
#    plugins = rabbitmq_management,rabbitmq_stomp