server:
  port: 6001
  servlet:
    context-path: /api
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    open-in-view: false
  datasource:
    url: jdbc:postgresql://172.20.10.4:5432/postgres
    username: postgres
    password: q987654321

security:
  oauth2:
    resource:
      user-info-uri: https://hexolink.lat/user-profile

host: authentication-service

logging:
  level:
    sql: debug
    root: debug
    web: debug
