name: Deploy MultiK8s
on:
  push:
    branches:
      - master

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          
      - name: Maven Package
        run: mvn -B clean package -DskipTests 
        
      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: hexolink-4a945

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: hexolink
          location: europe-central2-a

      - name: Build
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t noxior/auth-service:latest -t noxior/auth-service:${{ env.SHA }} -f ./auth-service/Dockerfile ./auth-service
          docker build -t noxior/messenger:latest -t noxior/messenger:${{ env.SHA }} -f ./messenger/Dockerfile ./messenger

      - name: Push
        run: |-
          docker push noxior/auth-service:latest
          docker push noxior/messenger:latest
          
          docker push noxior/auth-service:${{ env.SHA }}
          docker push noxior/messenger:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployment/auth-service-deployment auth-service=noxior/auth-service:${{ env.SHA }}
          kubectl set image deployment/messenger-deployment messenger=noxior/messenger:${{ env.SHA }}